/*DROP SEQUENCE SQ_SKT_FUNCIONARIO;

DROP SEQUENCE SQ_SKT_CARGO;

DROP SEQUENCE SQ_SKT_FUNC_CARGO;

DROP SEQUENCE SQ_SKT_FUNC_CARGO_QUESTION;

DROP SEQUENCE SQ_SKT_QUESTIONARIO;

DROP SEQUENCE SQ_SKT_QUESTOES;

DROP SEQUENCE SQ_SKT_QUESTION_QUESTOES;

DROP SEQUENCE SQ_SKT_RESPOSTAS;*/

CREATE SEQUENCE SQ_SKT_CARGO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SQ_SKT_FUNC_CARGO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SQ_SKT_FUNCIONARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SQ_SKT_FUNC_CARGO_QUESTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SQ_SKT_QUESTIONARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SQ_SKT_QUESTOES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SQ_SKT_QUESTION_QUESTOES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SQ_SKT_RESPOSTAS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;